[package]
name = "lyra"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["evolution","execution","learning","memory"]

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
lyra-evolution = { version = "0.1.0", path = "evolution" }
lyra-execution = { version = "0.1.0", path = "execution" }
lyra-learning = { version = "0.1.0", path = "learning" }
lyra-memory = { version = "0.1.0", path = "memory" }
ratatui = { version = "0.30.2", features = ["unstable-rendered-line-info"] }
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["rt-multi-thread"] }
toml = "1.1.6"
