//! The unified capability model (C1): everything the agent can do, whatever
//! it's made of, described the same way.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Where a capability comes from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CapabilityKind {
    /// Built into lyra (the memory tools).
    NativeTool,
    /// A tool generated by evolution from other tools.
    Composite,
    /// An operation from an OpenAPI description.
    OpenApi,
    /// A tool from an MCP server.
    Mcp,
    /// A workflow (phases the planner follows).
    Workflow,
    /// A learned skill (a procedure plan steps can follow).
    Skill,
    /// A helper agent for plan steps.
    Subagent,
}

impl CapabilityKind {
    /// Whether the model can call it as a function. Workflows, skills and
    /// subagents are used by the planner instead.
    pub fn callable(self) -> bool {
        matches!(self, Self::NativeTool | Self::Composite | Self::OpenApi | Self::Mcp)
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::NativeTool => "native",
            Self::Composite => "composite",
            Self::OpenApi => "openapi",
            Self::Mcp => "mcp",
            Self::Workflow => "workflow",
            Self::Skill => "skill",
            Self::Subagent => "subagent",
        }
    }
}

/// How much harm a capability can do (C4). Decided by Rust, not the model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RiskLevel {
    ReadOnly,
    /// Small, easily undone changes (a note, a memory).
    LowWrite,
    Write,
    Destructive,
    /// Changes to the agent itself, credentials, money, other people.
    Privileged,
}

impl RiskLevel {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ReadOnly => "read_only",
            Self::LowWrite => "low_write",
            Self::Write => "write",
            Self::Destructive => "destructive",
            Self::Privileged => "privileged",
        }
    }
}

/// Something a capability needs before it can run, and how to get it (C7).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CapabilityRequirement {
    /// What's needed, e.g. `memory id`, `projectId`.
    pub entity: String,
    /// A capability that finds it.
    pub resolution_capability: Option<String>,
}

/// How to check a mutating capability did what it says (C9): call
/// `capability` with `arguments` (where `{{result.x}}` and `{{args.x}}` are
/// filled from the call being verified) and test its output with
/// `success_expression` (`contains:…`, `exists:path`, `equals:path=value`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VerificationRule {
    pub capability: String,
    pub arguments: Value,
    pub success_expression: String,
}

/// Operational facts (C3). The numbers come from usage history.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CapabilityMetadata {
    pub destructive: bool,
    pub idempotent: bool,
    pub requires_approval: bool,
    pub average_latency_ms: Option<u64>,
    pub success_rate: Option<f32>,
    /// Money per call, if it costs any.
    pub cost: Option<f32>,
    pub verification: Option<VerificationRule>,
    pub requirements: Vec<CapabilityRequirement>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Capability {
    /// Unique, e.g. `memory_recall`, `pmi.tasks.create`.
    pub id: String,
    /// The name the model calls it by (function names can't contain dots).
    pub name: String,
    pub description: String,
    pub kind: CapabilityKind,
    /// JSON schema of its arguments.
    pub input_schema: Value,
    pub output_schema: Option<Value>,
    pub risk: RiskLevel,
    /// Permissions it needs, e.g. `memory.write`, `pmi.tasks.write`.
    pub permissions: Vec<String>,
    pub tags: Vec<String>,
    pub enabled: bool,
    /// The provider it belongs to (an OpenAPI or MCP source name, `native`, …).
    pub source: String,
    pub metadata: CapabilityMetadata,
}

impl Capability {
    pub fn new(id: &str, kind: CapabilityKind, description: &str, risk: RiskLevel) -> Self {
        Self {
            id: id.into(),
            name: function_name(id),
            description: description.into(),
            kind,
            input_schema: serde_json::json!({ "type": "object", "properties": {} }),
            output_schema: None,
            risk,
            permissions: Vec::new(),
            tags: Vec::new(),
            enabled: true,
            source: kind.as_str().into(),
            metadata: CapabilityMetadata {
                destructive: risk >= RiskLevel::Destructive,
                idempotent: risk == RiskLevel::ReadOnly,
                ..Default::default()
            },
        }
    }

    /// The text discovery searches: id, description, tags.
    pub fn search_text(&self) -> String {
        format!("{} {} {} {}", self.id.replace(['.', '_', '-'], " "), self.description, self.tags.join(" "), self.kind.as_str())
    }

    /// The OpenAI-style function definition for the model.
    pub fn definition(&self) -> Value {
        serde_json::json!({
            "type": "function",
            "function": { "name": self.name, "description": self.description, "parameters": self.input_schema },
        })
    }
}

/// A function name from an id: letters, digits and `_` only, at most 64 characters.
pub fn function_name(id: &str) -> String {
    let mut name: String = id.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect();
    name.truncate(64);
    name
}

/// Whether a capability can be used right now (C8).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CapabilityHealth {
    #[default]
    Healthy,
    /// Works but often fails or is slow lately.
    Degraded,
    /// Can't be reached; left out of discovery and planning.
    Unavailable,
}

impl CapabilityHealth {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Healthy => "healthy",
            Self::Degraded => "degraded",
            Self::Unavailable => "unavailable",
        }
    }
}

/// One invocation (C5).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CapabilityUsage {
    pub capability_id: String,
    pub run_id: Option<uuid::Uuid>,
    pub success: bool,
    pub duration_ms: u64,
    pub retries: u32,
    /// A short, normalized error kind: `permission`, `timeout`, `not_found`, …
    pub error_code: Option<String>,
    pub error: Option<String>,
}

/// What the usage history says about one capability.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CapabilityStats {
    pub uses: u64,
    pub successes: u64,
    pub average_latency_ms: Option<u64>,
    /// Over the most recent uses only (for health).
    pub recent_success_rate: Option<f32>,
    /// The most common error kind, if any.
    pub common_error: Option<String>,
}

impl CapabilityStats {
    /// `(successes + 1) / (uses + 2)`: new capabilities start at 0.5.
    pub fn reliability(&self) -> f32 {
        (self.successes as f32 + 1.0) / (self.uses as f32 + 2.0)
    }

    pub fn success_rate(&self) -> Option<f32> {
        (self.uses > 0).then(|| self.successes as f32 / self.uses as f32)
    }
}

/// Normalize an error to a short kind for statistics.
pub fn error_code(error: &str) -> String {
    let e = error.to_lowercase();
    let tokens: Vec<&str> = e.split(|c: char| !c.is_ascii_alphanumeric()).collect();
    let has = |w: &[&str]| w.iter().any(|w| if w.chars().all(|c| c.is_ascii_digit()) { tokens.contains(w) } else { e.contains(w) });
    if has(&["timed out", "timeout"]) {
        "timeout"
    } else if has(&["permission", "denied", "forbidden", "unauthorized", "401", "403", "not allowed", "may not", "needs approval"]) {
        "permission"
    } else if has(&["not found", "no such", "unknown", "404", "doesn't exist", "no memory"]) {
        "not_found"
    } else if has(&["invalid", "bad arguments", "missing", "required", "400", "422", "parse"]) {
        "invalid_input"
    } else if has(&["rate limit", "429", "too many"]) {
        "rate_limit"
    } else if has(&["connection", "refused", "unavailable", "502", "503", "500", "reset"]) {
        "unavailable"
    } else {
        "other"
    }
    .into()
}
